### ISSUE TITLE
Create NFT's for Flight Academy awards ceremony

### ISSUE THREAD

**Issue by blakewest** [goldfinch-eng/mono#5]
## Problem Statement
It would be awesome to give Flight Academy participants NFT's. We were gonna use POAPs, but the POAP team seems to be backed up, and doesn't have time to talk to Goldfinch.

## Potential solutions
Could the community can spin up an NFT contract on Polygon or some other L2? Then we just need a way for people to claim. You could use a Merkle Distributor to let people claim, and could maybe create a simple front-end page (potentially using this repo). 

There may be other ways to do it then what I'm describing! What are people's thoughts?

**Comment by FuryJohnson** [comment]
A few questions before start: 

1. Do youwant to reserve the rights to make an additional mint (in case someone change the address)
2. For other graduate of the academy, will be another nft or the same?

Thank you!

**Comment by unordered-set** [comment]
also: could you please publish the list of public keys of participants? iirc it was not in the chain, right?

**Comment by blakewest** [comment]
@FuryJohnson ...
1.) No let's not worry about this
2.) Let's say there would be another NFT. I think if we had the ability to create different types of NFTs even within the same season that would be idea (which points to using an ERC-1155 rather than ERC-721), but don't think this is critical for now. Even just one NFT for everyone who completes it would be awesome. We don't have to overthink this.

@unordered-set yeah we can get that to you soon, but don't have it quite yet. The list was def not on-chain. But either way I think we'd use a Merkle Distributor (ie. what Uniswap did [here](https://github.com/Uniswap/merkle-distributor)). Unless there's some other way to distrubute NFT's to thousands of people cheaply...

**Comment by unordered-set** [comment]
Thank you very much for your reply. Great, i think we are on a same page and we can continue!

**Comment by unordered-set** [comment]
I think we are more or less ready with the contract.

Contract: 0xaF8291a7e1B481967E34d5C7AdFbd24c7dfA7A69

And minted NFT: 

![Screenshot_20211124_235731_io metamask](https://user-images.githubusercontent.com/78592281/143327159-4ba53bbf-43c3-4096-ab6e-adf147408a93.jpg)

**Comment by FuryJohnson** [comment]
@unordered-set , I think @blakewest can answer the question)

**Comment by blakewest** [comment]
Awesome! A few things...
 * What is your plan for the front-end claiming process right now? If you didn't have anything in mind, maybe we could make a simple page from our main app, like `app.goldfinch.finance/flight_academy_claim`
 * In terms of symbol / name, let's do... GFA-1 /  Goldfinch Flight Academy - 1. Because it is the first Flight Academy and we may do more in the future.
 * I see it's an ERC-721. So that means we'd have one option for art. @andrew-goldfinch I believe wanted to have 2-3 options for different levels. I know I said it's OK to just have one level, and it is! But I'm curious if it would be much extra work to deploy 1-2 additional ERC-721 contracts for the different levels? Or alternatively... deploy an ERC-1155? If it would be a hassle, then this is still great. But if it would be easy I think it could be cool.

### Follow up questions
@andrew-goldfinch how many types of participation NFT's would you want to give out? And if we want multiple, what exactly are they for (so that we could give unique symbols to each). If we're cool with just one type, let that be known too!

@andrew-goldfinch Do we have the art that we want to use? (whether for one type or multiple types)

@andrew-goldfinch can we get them the list of addresses that participated?

@unordered-set what email should we use to send you the list of addresses?

**Comment by unordered-set** [comment]
I think switching to ERC-1155 is a bit dangerous right now, because everything is already prepared and I'm a bit scared to start doing new things. Also, maintaining a long-standing contract is much more expensive. Doing one-shot hermetic minting contract is easy, repeating it easy as well. But when you are switching to ERC-1155 with a feature to add more possible tokens to it etc, you need an infrastructure to store private key, manage the contract etc.

I am more than happy to deploy additional contracts when needed instead. Or I can check more detailed about 1155 for the next graduation. And we can even back-fill it.

About my email: could you please reach me on UNORDERED_SET@TUTANOTA.COM . And just to confirm - in order to generate Merkle tree proofs there are two ways to do it. 
1) I'm generating it on my PC, and we are emailing / discording proof to each participant (not nice idea, but it helps is to keep public keys hidden, although I don't think it makes sense, because all of the LP token holders etc, you can easily get it from onchain)
2) we are generating the proof on the frontend on the fly. This makes the list of addresses visible to everyone, who wants to digg into the code.

I'm more into following 2) if you don't have any objections

**Comment by blakewest** [comment]
@unordered-set good points regarding ERC-1155. Yeah let's stick with the ERC-721. Let's see if we want to repeat and deploy 1 or 2 more. Need to wait on @andrew-goldfinch to give us the final answer here as well as the list of addresses.

Regarding the list of addresses, I don't have any issues with no. 2. While not **all** flight academy participants will be on-chain (since not all participated as LPs), many did, and the public key is not sensitive information anyway. Plus they'll be nothing else to really connect it to in the outside world, so I think it's fine. @andrew-goldfinch when you have finalized the address list (and NFT styles that each address should get), please email it over. 

@unordered-set what was your plan for the front-end claiming process?

Thanks! This is gonna be great!

**Comment by unordered-set** [comment]
@blakewest , frontend was mostly managed by @FuryJohnson . Overall, I've seen the code, it is straightforward. Connect Wallet, ensure that network is Polygon, press "MINT", show your token on OpenSea.
